version: "3"

services:
  web:
    build: src
    volumes:
      - ./src:/app
      - ./storage:/storage
    command: [ "flask", "run", "--host=0.0.0.0", "--port=80" ]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app

  worker:
    build: src
    volumes:
      - ./src:/app
      - ./storage:/storage
